import type { Lead, Template } from "./types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "ld_001",
    business: "Cedar & Sage Kitchen",
    industry: "Restaurant",
    location: "Austin, TX",
    email: "hello@cedarsage.com",
    hasWebsite: false,
    emailStatus: "valid",
    qualification: "pending",
    stage: "scraped",
    dateScraped: "2026-06-28",
    notes: "",
  },
  {
    id: "ld_002",
    business: "NorthPeak Roofing",
    industry: "Home Services",
    location: "Denver, CO",
    email: "info@northpeakroof.com",
    hasWebsite: true,
    emailStatus: "valid",
    qualification: "qualified",
    stage: "qualified",
    dateScraped: "2026-06-27",
    notes: "Old Wix site, terrible mobile. Strong candidate.",
  },
  {
    id: "ld_003",
    business: "Lumen Dental Studio",
    industry: "Healthcare",
    location: "Portland, OR",
    email: "front@lumendental.co",
    hasWebsite: true,
    emailStatus: "unknown",
    qualification: "qualified",
    stage: "demo_built",
    dateScraped: "2026-06-26",
    notes: "Wants a clean, trust-forward look.",
  },
  {
    id: "ld_004",
    business: "Rivet & Rove Barbershop",
    industry: "Personal Care",
    location: "Nashville, TN",
    email: "cuts@rivetrove.com",
    hasWebsite: false,
    emailStatus: "valid",
    qualification: "qualified",
    stage: "sent",
    dateScraped: "2026-06-24",
    dateSent: "2026-07-01",
    notes: "Sent demo Tue. Follow up Fri.",
    followUp: "2026-07-04",
  },
  {
    id: "ld_005",
    business: "Bright Loop Bookkeeping",
    industry: "Professional Services",
    location: "Remote",
    email: "team@brightloop.io",
    hasWebsite: true,
    emailStatus: "valid",
    qualification: "qualified",
    stage: "replied",
    dateScraped: "2026-06-20",
    dateSent: "2026-06-25",
    notes: "Replied — asked about pricing. Warm.",
  },
  {
    id: "ld_006",
    business: "Halcyon Yoga Collective",
    industry: "Fitness & Wellness",
    location: "San Diego, CA",
    email: "studio@halcyonyoga",
    hasWebsite: false,
    emailStatus: "invalid",
    qualification: "pending",
    stage: "scraped",
    dateScraped: "2026-06-29",
    notes: "",
  },
  {
    id: "ld_007",
    business: "Ironclad Auto Detailing",
    industry: "Automotive",
    location: "Phoenix, AZ",
    email: "book@ironcladdetail.com",
    hasWebsite: false,
    emailStatus: "valid",
    qualification: "rejected",
    stage: "scraped",
    dateScraped: "2026-06-22",
    notes: "Too small, no budget signal.",
  },
  {
    id: "ld_008",
    business: "Meridian SaaS Advisors",
    industry: "SaaS / Tech",
    location: "Remote",
    email: "hi@meridianadvisors.com",
    hasWebsite: true,
    emailStatus: "valid",
    qualification: "qualified",
    stage: "won",
    dateScraped: "2026-06-15",
    dateSent: "2026-06-19",
    notes: "Closed. $4.2k build.",
  },
  {
    id: "ld_009",
    business: "Wildflour Bakehouse",
    industry: "Restaurant",
    location: "Boulder, CO",
    email: "orders@wildflour.co",
    hasWebsite: false,
    emailStatus: "valid",
    qualification: "pending",
    stage: "scraped",
    dateScraped: "2026-06-30",
    notes: "",
  },
  {
    id: "ld_010",
    business: "Atlas Legal Group",
    industry: "Professional Services",
    location: "Chicago, IL",
    email: "contact@atlaslegal.com",
    hasWebsite: true,
    emailStatus: "valid",
    qualification: "qualified",
    stage: "viewed",
    dateScraped: "2026-06-21",
    dateSent: "2026-06-27",
    notes: "Opened demo 3x. No reply yet.",
    followUp: "2026-07-05",
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "tpl_001",
    name: "Restaurant — Warm / Luxury",
    description: "Appetite-driven, editorial, warm neutrals with rich imagery.",
    mood: "luxury",
    layoutStyle: "asymmetric / full-bleed",
    typography: "editorial serif",
    colorDirection: "earthy natural",
    animation: "subtle",
    sections: ["Hero", "Features", "Social Proof", "CTA", "Closing"],
  },
  {
    id: "tpl_002",
    name: "SaaS — Minimal / Futuristic",
    description: "Product-forward, high-contrast dark, crisp technical type.",
    mood: "futuristic",
    layoutStyle: "grid / contained",
    typography: "mono-accented technical",
    colorDirection: "high-contrast dark",
    animation: "expressive",
    sections: ["Hero", "Features", "Social Proof", "CTA"],
  },
  {
    id: "tpl_003",
    name: "Home Services — Bold / Trust",
    description: "Direct, conversion-first, strong CTAs and proof.",
    mood: "bold",
    layoutStyle: "grid / contained",
    typography: "clean sans-serif",
    colorDirection: "monochrome + single accent",
    animation: "subtle",
    sections: ["Hero", "Features", "Social Proof", "CTA", "Closing"],
  },
  {
    id: "tpl_004",
    name: "Wellness — Calm / Minimal",
    description: "Airy, soft, humanist type with generous whitespace.",
    mood: "minimal",
    layoutStyle: "asymmetric / contained",
    typography: "humanist warm",
    colorDirection: "warm neutrals",
    animation: "subtle",
    sections: ["Hero", "Features", "CTA", "Closing"],
  },
];
